name: Azure Node.js + React App Deploy

on:
  push:
    branches:
      - main  # or your active branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./client
      run: npm install

    - name: Build React app
      working-directory: ./client
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./server
      run: npm install

    - name: Copy React build to backend
      run: |
        rm -rf server/dist
        cp -r client/dist server/dist

    - name: Zip backend for deployment
      run: |
        cd server
        zip -r ../app.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: InstagramApp
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./app.zip
